### ISSUE TITLE
hoveredOver issue since upgrade to v2.0.2-beta.5

### ISSUE THREAD

**Issue by lpequignot** [newcat/baklavajs#323]
Hi, 

I was using baklava **.v2.0.2-beta.3** and I wanted to test **v2.0.2-beta.5** (to have blurry nodes fixes).
I have the following warning, as soon as a Node is created and displayed

`
[Vue warn]: injection "hoveredOver" not found. 
  at <NodeInterface node= 
`

I can't make connections anymore, I have the following error.

`runtime-core.esm-bundler.js:221 Uncaught TypeError: hoveredOver is not a function
    at Proxy.endHover (NodeInterface.vue:51:13)
    at _ctx.intf.port._createElementBlock.onPointerout._cache.<computed>._cache.<computed> (NodeInterface.vue:3:85)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:278:5)`

Do you have any idea what could be the problem?

Regards,

Louise

**Comment by lpequignot** [comment]
Hi,

I tested 2.1.1 this morning and investigated more about the issue. 
It was my mistake, I apologize, I have a CustomNodeRenderer  and when I did it I also copied the NodeInterface because I thought maybe I would need to override it.
By using 

```
import { Components } from "@baklavajs/renderer-vue"
const NodeInterface = Components.NodeInterface;
```
I no longer have the issue.

Best Regards,

Louise
